# dm - Core Application Configuration

config:
  app:
    name: "dm"
    version: "0.0.1"
    description: "A dotfile manager from heaven"

  paths:
    repo: "$HOME/projects/dm/.dotfiles/LMD"
    template: "$HOME/projects/dm/dm/templates/default/"
    backup: "$HOME/projects/dm/.dotfiles/backups"
    log: "$HOME/projects/dm/.dotfiles/logs"

  behavior:
    autoGit: false
    autoApply: false
    promptForConfirmation: true
