# dm - Core Application Configuration

config:
  app:
    name: "dm"
    version: "0.0.1"
    description: "A dotfile manager from heaven"

  paths:
    repo: "$HOME/temp/.dotfiles/LMD"
    backup: "$HOME/temp/.dotfiles/backups"
    log: "$HOME/.local/share/dm/logs"

  behavior:
    autoGit: false
    promptForConfirmation: true
